### PR TITLE
add search by email

### PR DESCRIPTION
**Pull request by pronix**

### CODE REVIEW

**Comment by paulnicholson** [comment]
Can you also include a spec that covers this change? Thanks!

**Comment by pronix** [comment]
Sorry, but i not find way for start your tests.

**Comment by paulnicholson** [comment]
`bundle exec rspec`

**Comment by pronix** [comment]
updated

**Comment by paulnicholson** [comment]
Closed by 35277cfb902cf26b43102d291718625ff8c88e85 and 942f346d30aa2c2be255937d3f31ab58b11d9a91.
I've also release 0.1.6 to rubygems.

**Pull request closed without merging**
